
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"  
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ConnectionStrings__DefaultConnection="Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data: 
